import "@assets/styles/globals.css";

import type { Metadata } from "next";
import localFont from "next/font/local";

const guardianFont = localFont({
  src: [
    {
      path: "../assets/fonts/guardiansans-regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/guardiansans-medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/fonts/guardiansans-semibold.woff",
      weight: "600",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={guardianFont.className}>{children}</body>
    </html>
  );
}
